server:
  port: 8080
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://101.201.100.133:3306/luoyu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: luoyu
      password: kadxZuMkhbiJi3vRv/Wx8EZZH59cl1MyJK8QQYyeY07qxUhHP19B+d4W3w2BwsdvcD7GpvXoToCXzpXKPP+APw==
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: config,stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALgO071J2f4Lyvs1H6UURyiLTuPjIsQpOpZAjWjn6YPGQy7fN+P023Ek2SENy/soCNaneW0HJztJ4MKPRGQGcBcCAwEAAQ==
      druid:
          # 初始化时建立物理连接的个数
          initial-size: 3
          # 连接池最小连接数
          min-idle: 3
          # 连接池最大连接数
          max-active: 20
          # 获取连接时最大等待时间，单位毫秒
          max-wait: 60000
          # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
          test-while-idle: true
          # 既作为检测的间隔时间又作为testWhileIdel执行的依据
          time-between-connect-error-millis: 60000
          # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
          min-evictable-idle-time-millis: 30000
          # 用来检测连接是否有效的sql 必须是一个查询语句
          # mysql中为 select 'x'
          # oracle中为 select 1 from dual
          validation-query: select 'x'
          # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
          test-on-borrow: false
          # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
          test-on-return: false
          # 是否缓存preparedStatement,mysql5.5+建议开启
          pool-prepared-statements: false
          # 当值大于0时poolPreparedStatements会自动修改为true
          max-pool-prepared-statement-per-connection-size: 20
          # 合并多个DruidDataSource的监控数据
          use-global-data-source-stat: false
          # 配置扩展插件
          filter:
              config:
                  enabled: true
          # 定时输出统计信息到日志中，并每次输出日志会导致清零（reset）连接池相关的计数器。
          time-between-log-stats-millis: 300000
          # 配置DruidStatFilter
          web-stat-filter:
              enabled: false
              url-pattern: '/*'
              exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
          # 配置DruidStatViewServlet
          stat-view-servlet:
              # 是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
              enabled: false
              url-pattern: '/druid/*'
              # IP白名单(没有配置或者为空，则允许所有访问)
              allow: 127.0.0.1,192.168.0.1
              # IP黑名单 (存在共同时，deny优先于allow)
              deny: 192.168.0.128
              # 禁用HTML页面上的“Reset All”功能
              reset-enable: false
              # 登录名
              login-username: admin
              # 登录密码
              login-password: admin
logging:
    level:
        # 需要打印log日志(有sql执行)的包
        com.example.springboot.mapper: debug
#mapper&& 通用mapper
mybatis:
    type-aliases-package: com.luoyu.dao.entity
    mapper-locations: classpath:mapper/**/*.xml
mapper:
    identity: MYSQL