server:
    port: 80

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/luoyu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: root
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 50
            max-wait-millis: 200

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        encoding: UTF-8
        mode: HTML
        check-template-location: true
        cache: false
        servlet:
            content-type: text/html
    banner:
        charset: UTF-8
        location: classpath:banner.txt

logging:
    config: classpath:log4j2-spring.xml
    level:
        com.luooyu: info